### PR TITLE
Update the web app definition to 1.1.0

### PR DESCRIPTION
**Pull request by mgreisen**

### CODE REVIEW

**Comment by psiinon** [comment]
Its not just a move is it, its an upgrade to v 1.1.0 :)

**Comment by mgreisen** [comment]
> Its not just a move is it, its an upgrade to v 1.1.0 :)

Your right. I think I will create a PR that just moves the original 1.0.0 spec over into the repo, then I'll rebase on that for this PR and in that way keep the history.

**Comment by mgreisen** [comment]
@psiinon rebased.

**Comment by ware** [comment]
Sorry I had to miss the meeting last week.  Why are we removing references to 'public'?  Just want to understand.

**Comment by mgreisen** [comment]
@ware The idea for this spec (as I understand it) is "how do I launch my service". A definition that points to an already running service does not make sense in this scenario. It might make sense for a testing tool, but not for a recipe on how to launch the service.

**Comment by ware** [comment]
Cool!  Makes sense to me @mgreisen.  I appreciate the explanation.

**Pull request merged**
