### PR TITLE
Ryan lead change

### PR DESCRIPTION
**Pull request by hythloda**

### CODE REVIEW

**Comment by hanabi62513** [comment]
このサイト いろんな人が入って気持ち悪いな

**Review by SecurityCRob — APPROVED** [review]
If the WG is cool with it, I'm cool with it.  I think we should strategize on how to re-energize the broader tooling work and also support SBOM moving forward.

**Comment by joshbressers** [comment]
I have no issue with this, but I think a PR isn't the right path forward. I think a message should go to the mailing list to set expectations and intent.

**Comment by hythloda** [comment]
> 

Love that idea! Going to send now! thanks @joshbressers

**Comment by ware** [comment]
> I have no issue with this, but I think a PR isn't the right path forward. I think a message should go to the mailing list to set expectations and intent.

I'll send something out today.

**Review by joshbressers — APPROVED** [review]

**Pull request merged**
